CXX = gcc
CXXFLAGS = -Wall

mini: 
		$(CXX) $(CXXFLAGS) main.c ./bubbleSort/bubblesort.c ./gnomeSort/gnomeSort.c ./radixSort/radixSort.c ./quickSort/quickSort.c ./heapSort/heapSort.c -o project
clear:
	rm project